### ISSUE TITLE
[BUG] Server didn't load match config after created the match

### ISSUE THREAD

**Issue by hoan111** [PhlexPlexico/G5API#43]
Hi! I want to figure out why after I used the API ./matches/create to create a match, I didn't see the game server received the rcon command include get5_loadmatch_url and get5_apikey. Have I missed something? I'm newbie. Thank you!

**Comment by PhlexPlexico** [comment]
Hi!

I believe if you check the console where the API is running, it should provide some more context. It checks if the server is available and get5 is active, then will only send to the server itself. Please make sure your passwords are correct, and the server IP is correct as well. Hostnames (e.g. example.com) should work, but I haven't extensively tested them. 

So yeah, check the console on the G5API server, and paste it here and we can take a look!

Thanks!

**Comment by hoan111** [comment]
I checked both the console and the response. The console showed status 200 OK and the response was "Match inserted successfully!". Then I saw the console from the game server, only cvar "get5_get_available" was sent and still no match config downloaded from the API server. The parameters I sent was: 
[
{
"server_id":1,
"team1_id":1,
"team2_id":2,
max_maps":1,
"skip_veto":true,
"side_type": "always_knife",
"private_match":false,
"enforce_teams": true,
"ignore_server": false
}
]
Is there something wrong here? I want to create BO1 match.
Thanks!

**Comment by PhlexPlexico** [comment]
By chance are you using an actual host? Not just running G5API from a localhost and that's it? Much like Get5-Web and Get5-api, they all require an actual hostname (like hosting on phlexplexi.co as an example). If you do not meet this requirement, the CS:GO server will not know where to send/receive the data, and will most likely cause it to fail.

Having the actual output log from the G5API server would be nicer to have, as it makes debugging a bit easier. But from the looks of the JSON you're sending, everything seems to be correct.

Thanks!

**Comment by PhlexPlexico** [comment]
If it's failing within the get5_web_available call, it should show in the error logs of the web server, as seen here:

https://github.com/PhlexPlexico/G5API/blob/master/utility/serverrcon.js#L43

Is it returning anything other than what is intended? It's possible that the call for it is failing, since I'm returning strings instead of a boolean. I'll take a peek into it whenever I have time, or if you can find a fix, feel free to make a PR :)

**Comment by PhlexPlexico** [comment]
Please try checking out the `available_fix` branch and let me know if that works:

https://github.com/PhlexPlexico/G5API/blob/available_fix/utility/serverrcon.js 

I've changed it to return an actual boolean instead of text, so it should fix it?

Thank you!

**Comment by PhlexPlexico** [comment]
Any update towards this?

**Comment by hoan111** [comment]
> Any update towards this?

Yeah I'm here but at this time I'm focusing on my CSGO tournament and set up for my new CSGO server so I don't have time to test it. Maybe tomorrow I will test it and let you know ^^
And thanks for your reply!

**Comment by PhlexPlexico** [comment]
Awesome! Thank you very much! Just as a heads up too, all the routes are more "RESTful" so there is no longer `/create` `/update` or `/delete`, they exist all under `/` and you should just the use the HTTP calls associated with everything (i.e. `POST` from `/create` is now just `POST` `/`)

Thanks for helping out!

**Comment by hoan111** [comment]
I tested your API but still no luck :( I created the match, the response is "Match inserted successfully", the console showed status 200 but still no new commands was sent to the game server. My game server and API server are running the same network, I'm using No-ip to create a DNS hostname for the API server. Should I run the API server and the game server on different network?
Thank you!

**Comment by PhlexPlexico** [comment]
Hmm. A few things to look at:

Are you running in TEST mode?
https://github.com/PhlexPlexico/G5API/blob/master/utility/serverrcon.js#L71
If you are, it automatically returns false. Is there any output from the server console? I believe the CS:GO server will shoot out the output of "status" if it's called remotely on its local console.

Worse comes to worse with that, try adding `console.log(get5Status)` one line 77 of that file, see if it outputs anything. Another thing you can check is to go `/servers/{server_id}/status` to check to see if the server is being reported as online by the website.

**Comment by PhlexPlexico** [comment]
So usually when you don't have a server provided in the match (`server_id`) it won't run anything related to the server. With that being said, it should output something on the game server console, or it will also output a console logs on the API server. If not, just add a console.log as aforementioned. That should work!

**Comment by hoan111** [comment]
Oh, too many new cool updates here! I will try it and let you know if it works. 
Thank you for your hard work!

**Comment by PhlexPlexico** [comment]
No problem! I just hope the new updates didn't break anything that's older now 👀

**Comment by PhlexPlexico** [comment]
Sooooo you were totally right in this, and I didn't do enough testing. 

I attempted to create a match through G5V, and it appears I did a few things wrong :)

1) The URL being sent used to be `req.get("host")` and if that wasn't configured, it would just send the URL as `localhost`. 
2) The URL was missing the entire API behind it. It would just send the URL, but not the config to the match.
3) The `get5_web_url` was completely wrong as well. 
4) There was some funky issues with the try-catch statements for sending and receiving messages.
5) There was even more issues with parsing responses (I didn't realize the the `L 10/21/20...` was sent back in the response as well.

So, I've modified the API to be more used with G5V right now, but I was thinking of breaking that out yet again. The URL being sent during the [create match](https://github.com/PhlexPlexico/G5API/blob/master/utility/serverrcon.js#L121) is now more attuned to using a reverse proxy through vue webpack, Buuuut I'm going to break it out into it's own URL.

To mitigate this, there is a new entry in the configs. `apiURL` is now intended to link to the main page of the G5API. This can be set as a reverse proxy (i.e. like it's done in G5V), or even be direct. This should now fix the problem of matches not being created.

**Comment by xe1os** [comment]
@PhlexPlexico what needs to be updated in the G5API config as i'm getting `Invalid Host Header` if i am trying to open G5V panel using sub domain. 

Below are the details updated in development.config
`"hostname": "http://xyz.xe1os.com,`
`"clientHome": "http://localhost:8080",`
`"apiURL": "http://localhost:8080/api/" `

Are these details proper? Do i need to update anything in G5V vue.config.js??

I basically want to make it work like yours [phlex.avidgamers.me:8080](url)

**Comment by PhlexPlexico** [comment]
Please see issue https://github.com/PhlexPlexico/G5V/issues/24 as I'm still awaiting reply and this issue isn't related! Thanks!

**Comment by PhlexPlexico** [comment]
Another thing to comment on this issue, please make sure your server has the two following options enabled:

`log on`
`sv_logecho 1`

This will ensure that it works.

**Comment by PhlexPlexico** [comment]
So, I've created a few new matches and have tested this as much as I possibly could with the plugin, as well as the API. I'm going to close this, and if you're still having issues feel free to re-open!

Thanks!

**Comment by hoan111** [comment]
Hello! Sorry I disappeared for a long time ago because I'm too lazy to boot into Linux and test your API @.@ So I have a question: Can I run this API and G5V on Windows OS instead of using Linux? I tried but I stuck at step migrating database. I really want to use your API and Web to organize my CS:GO tournament.
Thanks for your hard work!

**Comment by xe1os** [comment]
> Hello! Sorry I disappeared for a long time ago because I'm too lazy to boot into Linux and test your API @.@ So I have a question: Can I run this API and G5V on Windows OS instead of using Linux? I tried but I stuck at step migrating database. I really want to use your API and Web to organize my CS:GO tournament.
> Thanks for your hard work!

@hoan111 you can use WSL on windows to make this work.

**Comment by hoan111** [comment]
@xe1os  I know but I want to install both the API and G5V in internet cafe to work on LAN. They are using "Bootrom" technology (Boot on LAN) for all their machines. WSL require to restart the computer after enabled. If I restart the computer, everything will be reset. I don't want to boot from my HDD because it's too complicated to setup and change the hardware :((( I just use my HDD to store the game server and run it immediately.

**Comment by PhlexPlexico** [comment]
Considering its using node and yarn, yes you should be able to :) I believe all the packages are platform agnostic, so you shouldn't have to worry about the operating system you're running on. I think the wiki may have some basic install instructions for Windows, I forget. However, as long as you have Node and yarn installed, it shouldn't be a problem!

**Comment by hoan111** [comment]
Yes, I will find a solution. The problem just comes from the command line on package.json. I will try to follow the instruction. Thank you!

**Comment by PhlexPlexico** [comment]
Ahh I get it. I think one reason would be those pesky SQL flags that are required on instances or else the migration fails... I think if you call `SET MYSQL_FLAGS="-CONNECT_WITH_DB` and then remove them from the package.json, that should work. I'll think about getting some windows-specific package commands as well to run those import/exports on. Thanks for the heads up!

**Comment by hoan111** [comment]
Thank you! It worked
